### ISSUE TITLE
"false positives" 

### ISSUE THREAD

**Issue by quillie** [f321x/nostr-pow-provider#4]
Hey,

thanks again for making this great project public. I love it. 

As you know, I'm also running a tracking token bot -> https://primal.net/p/npub1nttrktvvhewwzmfdmyruxupx2hg5pxgzlakwuhepdzlm8cdakhrs9wkh4p

While studying this week's replies, I noticed two things. The thing is that the bot has a tendency towards "false positives". I will show you what I mean:

A) in note1q0mcpgxxvmqdj3r4r4mkd33l3mu6sd2my6ssesn44wrrlpfydj6q0jnw4k, the bot removed "?feature=shared" from the link. While not being really necessary, I guess this part does no harm and might confuse folks?

B) in note1pha49hn0824f275de0gtgy0et9yg07tjusyv68wr4xqvwl3y58kqvxnfnu, the bot removed "s=46", which is a reference to a certain scene in the video, right? I guess people won't be too please about that.

To be fair, this is not super urgent but something that could be improved in a future version.

cheerz

**Comment by f321x** [comment]
Hey @quillie 
this is the wrong repository :) Also fyi there is a Referate repository for the parsing oft the tracking tokens too (f321x/untrack-rs), this issue would probably best fit in there.
I agree this is not perfect but was not motivated to fix it yet.
At one point I wanted to use this really nice, curated list of tracking tokens https://rules2.clearurls.xyz/data.minify.json
Then the bot would work perfectly I guess, feel free to open PRs, I currently have different priorities.
Closing this issue here, actually already have a fitting issue open :D 
https://github.com/f321x/untrack-rs/issues/1
